version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: banco
    environment:
      POSTGRES_USER: mercadinho
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
